### ISSUE TITLE
problem running examples

### ISSUE THREAD

**Issue by luiz1989** [msteyvers/matjags#15]
Hi, I'm having some issues running the examples from matjags. 
Possibly something simple, but since I'm not well familiarized with this interface I was not able to solve.
Someone could help with that ?

Example 1
--------------------------------------------------------------
Running JAGS...
Running chain 1 (serial execution)
Running chain 2 (serial execution)
Running chain 3 (serial execution)
Running chain 4 (serial execution)
Running chain 5 (serial execution)
Running chain 6 (serial execution)
Running chain 7 (serial execution)
Error using matjags (line 291)
Error from dos environment:
c:\temp\jagstmp>setlocal

c:\temp\jagstmp>set PATH=C:\Program Files\JAGS\JAGS-4.3.0\x64\bin\;C:\Program Files\MATLAB\MATLAB Production
Server\R2015a\bin\win64;C:\Program Files (x86)\Common
Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
Files (x86)\QuickTime\QTSystem\;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\runtime\win64;C:\Program
Files\MATLAB\MATLAB Production Server\R2015a\bin;C:\Program Files\MATLAB\MATLAB Production
Server\R2015a\polyspace\bin;C:\Program Files\MATLAB\R2009a\bin;C:\Program Files\MATLAB\R2009a\bin\win64;C:\Program
Files\JAGS\JAGS-4.3.0\x64\bin;C:\Program
Files\JAGS\JAGS-3.3.0\x64\bin;C:\Users\luizo\AppData\Local\Microsoft\WindowsApps;

c:\temp\jagstmp>set LTDL_LIBRARY_PATH=C:\Program Files\JAGS\JAGS-4.3.0\x64\modules

c:\temp\jagstmp>cls

c:\temp\jagstmp>jags-terminal jagscript1.cmd
Welcome to JAGS 4.3.0 on Wed Oct 09 09:42:01 2019
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Loading module: wiener: Não foi possível encontrar o módulo especificado. (not possibly to find specified module)
Loading module: glm: ok
Loading module: dic: ok
Failed to open file C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin\Rate_1.txt

Error in Example1 (line 51)
[samples, stats, structArray] = matjags( ...

**Comment by drbenvincent** [comment]
No insights from me I'm afraid. I've stopped using JAGS, and also Matlab in fact. I'd maybe try running one of the JAGS examples. If that won't work then it might be a JAGS installation issue?
