### ISSUE TITLE
idea: return an mcmc object?

### ISSUE THREAD

**Issue by drbenvincent** [msteyvers/matjags#8]
So this is a suggestion and I'd like feedback on whether people would find this useful.

In my use of JAGS and matjags, I have basically bundled up the output of matjags into a 'mcmc container' class. I've given this some useful methods such as:
- printing an R hat convergence summary
- plotting univariate summary stats (stem and leaf style)
- plotting mcmc chains for inspection
- various get methods to access the mcmc samples. Chains can be kept separate, or concatenated. You can ask for specific indexes of multidimensional arrays

This is an evolving example https://github.com/drbenvincent/delay-discounting-analysis/blob/master/ddToolbox/classes/JAGSmcmc.m Bear in mind that it contains project-specific elements, and that I'm still on the OOP learning curve, but I've found this approach useful.

Another reason why I am doing this is, for my analysis code (see link above) I want people to be able to use either JAGS or STAN. So if we have a general mcmc container class (an interface) then I can just implement a jags or a stan concrete class. I've started to do this, but it's not finished.

I'd be interested in hearing from people as to whether this would be a useful addition to matjags? Maybe it's something to add to the matjags project, maybe it's a separate project that wraps around matjags? Feel free to add criticism / suggestions.

**Comment by msteyvers** [comment]
Benjamin,
Still traveling ... hence the slow reply. I really like the ideas you propose -- develop one interface from which JAGS, STAN, or other packages can be called. I have added you as a collaborator on the Matjags project and you should feel free to make these changes. I don't do a lot of work myself with JAGS (my students do) and I think you are in a better position to develop the matjags project.
-Mark
